### ISSUE TITLE
Crash on `:CommandT` after a buffer has been manually removed

### ISSUE THREAD

**Issue by derenio** [wincent/command-t#166]
I'm experiencing a crash:

```
/home/derenio/.vim/bundle/Command-T/ruby/command-t/match_window.rb:47:in `number'
/home/derenio/.vim/bundle/Command-T/ruby/command-t/match_window.rb:47:in `initialize'
/home/derenio/.vim/bundle/Command-T/ruby/command-t/controller.rb:300:in `new'
/home/derenio/.vim/bundle/Command-T/ruby/command-t/controller.rb:300:in `show'
/home/derenio/.vim/bundle/Command-T/ruby/command-t/controller.rb:113:in `show_file_finder'
Error detected while processing function commandt#CommandTShowFileFinder:
line    2:
Vim::DeletedBufferError: attempt to refer to deleted buffer
```

The above error occur on `:CommandT` after I run my function removing buffers that aren't visible in any open window or tab.
Here is the function:

```viml
"Remove hidden buffers
function! HiddenBuffersWipeout()
	" list of *all* buffer numbers
	let l:buffers = []
	for i in range(1, bufnr('$'))
		if bufexists(i)
			call add(l:buffers, i)
		endif
	endfor

	" what tab page are we in?
	let l:currentTab = tabpagenr()
	try
		" go through all tab pages
		let l:tab = 0
		while l:tab < tabpagenr('$')
			let l:tab += 1
			execute 'tabnext' l:tab

			" go through all windows
			let l:win = 0
			while l:win < winnr('$')
				let l:win += 1
				" whatever buffer is in this window in this tab, remove it from
				" l:buffers list
				let l:thisbuf = winbufnr(l:win)
				call remove(l:buffers, index(l:buffers, l:thisbuf))
			endwhile
		endwhile

		" if there are any buffers left, delete them
		if len(l:buffers)
			execute 'bwipeout' join(l:buffers)
		endif
	finally
		" go back to our original tab page
		execute 'tabnext' l:currentTab
	endtry
endfunction
```

**Comment by wincent** [comment]
Looks like it's throwing an error because you've deleted Command-T's
hidden, unlisted buffer. I'd suggest that you shouldn't do that, but I can
also try to modify Command-T so that it at least falls back gracefully
under this circumstance.

Thanks for the detailed report!

**Comment by wincent** [comment]
I've implemented a work-around on the `next` branch, so this won't blow up any more. But I would suggest that you don't delete unlisted buffers, as they are usually unlisted for good reason.

Thanks once again for the report!
