### ISSUE TITLE
Calling Command-T from a new tab throws an 'Invalid Range' error.

### ISSUE THREAD

**Issue by leonschreuder** [wincent/command-t#266]
In Neovim I get an error in command-t after opening a new tab and trying to call command-t. After that, command-t is dead.
It could be a NeoVim problem of course, but can you tell what is the actual problem command-t has?

```
/home/lemo7242/.linuxbrew/lib/ruby/gems/2.3.0/gems/neovim-0.2.4/lib/neovim/session.rb:135:in `block in request'                                                                                                                         
/home/lemo7242/.linuxbrew/lib/ruby/gems/2.3.0/gems/neovim-0.2.4/lib/neovim/session.rb:201:in `main_thread_only'
/home/lemo7242/.linuxbrew/lib/ruby/gems/2.3.0/gems/neovim-0.2.4/lib/neovim/session.rb:126:in `request'
/home/lemo7242/.linuxbrew/lib/ruby/gems/2.3.0/gems/neovim-0.2.4/lib/neovim/api.rb:80:in `call'
/home/lemo7242/.linuxbrew/lib/ruby/gems/2.3.0/gems/neovim-0.2.4/lib/neovim/client.rb:25:in `method_missing'
/home/lemo7242/.linuxbrew/lib/ruby/gems/2.3.0/gems/neovim-0.2.4/lib/neovim/ruby_provider/vim.rb:13:in `public_send'
/home/lemo7242/.linuxbrew/lib/ruby/gems/2.3.0/gems/neovim-0.2.4/lib/neovim/ruby_provider/vim.rb:13:in `method_missing'
/home/lemo7242/.vim/bundle/command-t/ruby/command-t/match_window.rb:283:in `focus_window'
/home/lemo7242/.vim/bundle/command-t/ruby/command-t/match_window.rb:47:in `block in initialize'
/home/lemo7242/.vim/bundle/command-t/ruby/command-t/match_window.rb:46:in `each'
/home/lemo7242/.vim/bundle/command-t/ruby/command-t/match_window.rb:46:in `map'
/home/lemo7242/.vim/bundle/command-t/ruby/command-t/match_window.rb:46:in `initialize'
/home/lemo7242/.vim/bundle/command-t/ruby/command-t/controller.rb:354:in `new'
/home/lemo7242/.vim/bundle/command-t/ruby/command-t/controller.rb:354:in `show'
/home/lemo7242/.vim/bundle/command-t/ruby/command-t/controller.rb:146:in `show_file_finder'
(eval):3:in `show_file_finder'
/home/lemo7242/.linuxbrew/lib/ruby/gems/2.3.0/gems/neovim-0.2.4/lib/neovim/ruby_provider.rb:29:in `<main>'
/home/lemo7242/.linuxbrew/lib/ruby/gems/2.3.0/gems/neovim-0.2.4/lib/neovim/ruby_provider.rb:29:in `eval'
/home/lemo7242/.linuxbrew/lib/ruby/gems/2.3.0/gems/neovim-0.2.4/lib/neovim/ruby_provider.rb:29:in `block (2 levels) in __define_ruby_execute'
/home/lemo7242/.linuxbrew/lib/ruby/gems/2.3.0/gems/neovim-0.2.4/lib/neovim/ruby_provider.rb:77:in `block (3 levels) in __wrap_client'
/home/lemo7242/.linuxbrew/lib/ruby/gems/2.3.0/gems/neovim-0.2.4/lib/neovim/ruby_provider.rb:114:in `__with_redirect_streams'
/home/lemo7242/.linuxbrew/lib/ruby/gems/2.3.0/gems/neovim-0.2.4/lib/neovim/ruby_provider.rb:76:in `block (2 levels) in __wrap_client'
/home/lemo7242/.linuxbrew/lib/ruby/gems/2.3.0/gems/neovim-0.2.4/lib/neovim/ruby_provider.rb:96:in `__with_vim_constant'
/home/lemo7242/.linuxbrew/lib/ruby/gems/2.3.0/gems/neovim-0.2.4/lib/neovim/ruby_provider.rb:75:in `block in __wrap_client'
/home/lemo7242/.linuxbrew/lib/ruby/gems/2.3.0/gems/neovim-0.2.4/lib/neovim/ruby_provider.rb:89:in `__with_globals'
/home/lemo7242/.linuxbrew/lib/ruby/gems/2.3.0/gems/neovim-0.2.4/lib/neovim/ruby_provider.rb:74:in `__wrap_client'
/home/lemo7242/.linuxbrew/lib/ruby/gems/2.3.0/gems/neovim-0.2.4/lib/neovim/ruby_provider.rb:28:in `block in __define_ruby_execute'
/home/lemo7242/.linuxbrew/lib/ruby/gems/2.3.0/gems/neovim-0.2.4/lib/neovim/plugin/handler.rb:58:in `call'
/home/lemo7242/.linuxbrew/lib/ruby/gems/2.3.0/gems/neovim-0.2.4/lib/neovim/host.rb:104:in `block in wrap_plugin_handler'
/home/lemo7242/.linuxbrew/lib/ruby/gems/2.3.0/gems/neovim-0.2.4/lib/neovim/host.rb:63:in `handle'
Error detected while processing function commandt#FileFinder[2]..provider#ruby#Call:
line   17:
W, [2017-01-17T11:25:40.442220 #30361]  WARN -- Neovim::Host: got unexpected error #<ArgumentError: Vim(wincmd):E16: Invalid range>
Vim(wincmd):E16: Invalid range
Error detected while processing function commandt#FileFinder:
line    2:
E171: Missing :endif
```

**Comment by jakalope** [comment]
I am also using neovim. I get the same error on files I try to open that were open when I had to do a forced reboot without closing neovim first.

```
/var/lib/gems/1.9.1/gems/neovim-0.4.0/lib/neovim/session.rb:102:in `block in request'
/var/lib/gems/1.9.1/gems/neovim-0.4.0/lib/neovim/session.rb:154:in `main_thread_only'
/var/lib/gems/1.9.1/gems/neovim-0.4.0/lib/neovim/session.rb:93:in `request'
/var/lib/gems/1.9.1/gems/neovim-0.4.0/lib/neovim/session/api.rb:61:in `call'
/var/lib/gems/1.9.1/gems/neovim-0.4.0/lib/neovim/remote_object.rb:27:in `method_missing'
/var/lib/gems/1.9.1/gems/neovim-0.4.0/lib/neovim/window.rb:27:in `height='
/home/jake/.vim/bundle/command-t/ruby/command-t/lib/command-t/match_window.rb:349:in `block in restore_window_views'
/home/jake/.vim/bundle/command-t/ruby/command-t/lib/command-t/match_window.rb:346:in `each'
/home/jake/.vim/bundle/command-t/ruby/command-t/lib/command-t/match_window.rb:346:in `restore_window_views'
/home/jake/.vim/bundle/command-t/ruby/command-t/lib/command-t/match_window.rb:198:in `unload'
/home/jake/.vim/bundle/command-t/ruby/command-t/lib/command-t/match_window.rb:194:in `leave'
/home/jake/.vim/bundle/command-t/ruby/command-t/lib/command-t/controller.rb:155:in `hide'
/home/jake/.vim/bundle/command-t/ruby/command-t/lib/command-t/controller.rb:236:in `accept_selection'
(eval):3:in `accept_selection'
eval:1:in `<main>'
/var/lib/gems/1.9.1/gems/neovim-0.4.0/lib/neovim/ruby_provider.rb:55:in `eval'
/var/lib/gems/1.9.1/gems/neovim-0.4.0/lib/neovim/ruby_provider.rb:55:in `block (2 levels) in __define_ruby_execute'
/var/lib/gems/1.9.1/gems/neovim-0.4.0/lib/neovim/ruby_provider.rb:110:in `block in __wrap_client'
/var/lib/gems/1.9.1/gems/neovim-0.4.0/lib/neovim/ruby_provider.rb:118:in `__with_exception_handling'
/var/lib/gems/1.9.1/gems/neovim-0.4.0/lib/neovim/ruby_provider.rb:109:in `__wrap_client'
/var/lib/gems/1.9.1/gems/neovim-0.4.0/lib/neovim/ruby_provider.rb:54:in `block in __define_ruby_execute'
/var/lib/gems/1.9.1/gems/neovim-0.4.0/lib/neovim/plugin/handler.rb:51:in `call'
/var/lib/gems/1.9.1/gems/neovim-0.4.0/lib/neovim/plugin/handler.rb:51:in `call'
/var/lib/gems/1.9.1/gems/neovim-0.4.0/lib/neovim/host.rb:96:in `block in wrap_plugin_handler'
/var/lib/gems/1.9.1/gems/neovim-0.4.0/lib/neovim/host.rb:53:in `call'
/var/lib/gems/1.9.1/gems/neovim-0.4.0/lib/neovim/host.rb:53:in `handle'
Error detected while processing function commandt#private#AcceptSelection[1]..provider#ruby#Call:
line   17:
ArgumentError: Vim:E315: ml_get: invalid lnum: 16
```

**Comment by wincent** [comment]
I'm using Command-T in Neovim every day and have never seen either of these. Going to need some kind of reliable repro info.

**Comment by wincent** [comment]
Given the big rewrite for v6.0.x, I'm closing all older issues as there is unlikely to be anything significant happening on [the `5-x-devel` branch](https://github.com/wincent/command-t/tree/5-x-devel) from here on[^patches]. Feedback issue for 6.0.x is here:

- https://github.com/wincent/command-t/issues/393

[^patches]: Patches and PRs would be welcome, but my personal efforts are going to be directed towards `main`.
