### ISSUE TITLE
Command-T stops working after deleting its hidden buffer

### ISSUE THREAD

**Issue by JavierParra** [wincent/command-t#342]
As the title mentions, command-t stops working after deleting its buffer.

I'm using neovim v0.3.0.

Steps to reproduce:
 - Open any file.
 - Run `:CommandT`
 - Close command-t window
 - Run `%bwipe`
 - Run `:CommandT`
 - You should get the following error:

``` 
.vim/bundle/command-t/ruby/command-t/lib/command-t/match_window.rb:157:in `rescue in buffer_number'
 .vim/bundle/command-t/ruby/command-t/lib/command-t/match_window.rb:155:in `buffer_number'
 .vim/bundle/command-t/ruby/command-t/lib/command-t/match_window.rb:76:in `initialize'
 .vim/bundle/command-t/ruby/command-t/lib/command-t/controller.rb:366:in `new'
 .vim/bundle/command-t/ruby/command-t/lib/command-t/controller.rb:366:in `show'
 .vim/bundle/command-t/ruby/command-t/lib/command-t/controller.rb:147:in `show_file_finder'
(eval):3:in `show_file_finder'
eval:1:in `<main>'
/usr/local/lib/ruby/gems/2.5.0/gems/neovim-0.7.1/lib/neovim/ruby_provider.rb:45:in `eval'
/usr/local/lib/ruby/gems/2.5.0/gems/neovim-0.7.1/lib/neovim/ruby_provider.rb:45:in `block (2 levels) in __define_ruby_execute'
/usr/local/lib/ruby/gems/2.5.0/gems/neovim-0.7.1/lib/neovim/ruby_provider.rb:101:in `block (2 levels) in __wrap_client'
/usr/local/lib/ruby/gems/2.5.0/gems/neovim-0.7.1/lib/neovim/ruby_provider.rb:123:in `__with_std_streams'
/usr/local/lib/ruby/gems/2.5.0/gems/neovim-0.7.1/lib/neovim/ruby_provider.rb:100:in `block in __wrap_client'
/usr/local/lib/ruby/gems/2.5.0/gems/neovim-0.7.1/lib/neovim/ruby_provider.rb:109:in `__with_exception_handling'
/usr/local/lib/ruby/gems/2.5.0/gems/neovim-0.7.1/lib/neovim/ruby_provider.rb:99:in `__wrap_client'
/usr/local/lib/ruby/gems/2.5.0/gems/neovim-0.7.1/lib/neovim/ruby_provider.rb:44:in `block in __define_ruby_execute'
/usr/local/lib/ruby/gems/2.5.0/gems/neovim-0.7.1/lib/neovim/plugin/handler.rb:51:in `call'
/usr/local/lib/ruby/gems/2.5.0/gems/neovim-0.7.1/lib/neovim/host.rb:98:in `block in wrap_plugin_handler'
/usr/local/lib/ruby/gems/2.5.0/gems/neovim-0.7.1/lib/neovim/host.rb:36:in `handle'
/usr/local/lib/ruby/gems/2.5.0/gems/neovim-0.7.1/lib/neovim/host.rb:28:in `block in run'
Error detected while processing function commandt#FileFinder:
line    2:
NameError: uninitialized constant Vim::DeletedBufferError
```

**Edit**: Pinpointed the real culprit and simplified steps to reproduce.

**Comment by JavierParra** [comment]
The following simple (albeit ugly) patch fixes the error:
[deleted-buffer.diff.txt](https://github.com/wincent/command-t/files/2397746/deleted-buffer.diff.txt)

**Comment by wincent** [comment]
Awesome. Thanks. It may be ugly, but error-handling often is.
