### ISSUE TITLE
Deal with incompatible undo files

### ISSUE THREAD

**Issue by wincent** [wincent/command-t#381]
Which can happen if Neovim and Vim run with the same directory and the same files. (In my own set-up, I will make these not share `undo` etc directories.)

```
/Library/Ruby/Gems/2.6.0/gems/neovim-0.8.1/lib/neovim/session.rb:72:in `block in request'
/Library/Ruby/Gems/2.6.0/gems/neovim-0.8.1/lib/neovim/session.rb:117:in `main_thread_only'
/Library/Ruby/Gems/2.6.0/gems/neovim-0.8.1/lib/neovim/session.rb:55:in `request'
/Library/Ruby/Gems/2.6.0/gems/neovim-0.8.1/lib/neovim/api.rb:84:in `call'
/Library/Ruby/Gems/2.6.0/gems/neovim-0.8.1/lib/neovim/client.rb:39:in `method_missing'
/Library/Ruby/Gems/2.6.0/gems/neovim-0.8.1/lib/neovim/ruby_provider/vim.rb:19:in `public_send'
/Library/Ruby/Gems/2.6.0/gems/neovim-0.8.1/lib/neovim/ruby_provider/vim.rb:19:in `method_missing'
/Users/wincent/code/wincent/aspects/vim/files/.vim/pack/bundle/opt/command-t/ruby/command-t/lib/command-t/finder.rb:43:
in `open_selection'
/Users/wincent/code/wincent/aspects/vim/files/.vim/pack/bundle/opt/command-t/ruby/command-t/lib/command-t/controller.rb
:473:in `open_selection'
/Users/wincent/code/wincent/aspects/vim/files/.vim/pack/bundle/opt/command-t/ruby/command-t/lib/command-t/controller.rb
:238:in `accept_selection'
(eval):3:in `accept_selection'
eval:1:in `<main>'
/Library/Ruby/Gems/2.6.0/gems/neovim-0.8.1/lib/neovim/ruby_provider.rb:47:in `eval'
/Library/Ruby/Gems/2.6.0/gems/neovim-0.8.1/lib/neovim/ruby_provider.rb:47:in `block (2 levels) in __define_ruby_execute
'
/Library/Ruby/Gems/2.6.0/gems/neovim-0.8.1/lib/neovim/ruby_provider.rb:103:in `block (2 levels) in __wrap_client'
/Library/Ruby/Gems/2.6.0/gems/neovim-0.8.1/lib/neovim/ruby_provider.rb:125:in `__with_std_streams'
/Library/Ruby/Gems/2.6.0/gems/neovim-0.8.1/lib/neovim/ruby_provider.rb:102:in `block in __wrap_client'
/Library/Ruby/Gems/2.6.0/gems/neovim-0.8.1/lib/neovim/ruby_provider.rb:111:in `__with_exception_handling'
/Library/Ruby/Gems/2.6.0/gems/neovim-0.8.1/lib/neovim/ruby_provider.rb:101:in `__wrap_client'
/Library/Ruby/Gems/2.6.0/gems/neovim-0.8.1/lib/neovim/ruby_provider.rb:46:in `block in __define_ruby_execute'
/Library/Ruby/Gems/2.6.0/gems/neovim-0.8.1/lib/neovim/plugin/handler.rb:51:in `call'
/Library/Ruby/Gems/2.6.0/gems/neovim-0.8.1/lib/neovim/host.rb:101:in `block in wrap_plugin_handler'
/Library/Ruby/Gems/2.6.0/gems/neovim-0.8.1/lib/neovim/host.rb:37:in `handle'
/Library/Ruby/Gems/2.6.0/gems/neovim-0.8.1/lib/neovim/host.rb:29:in `block in run'
Error detected while processing function commandt#private#AcceptSelection:
line    1:
RuntimeError: Vim(edit):E824: Incompatible undo file: /Users/wincent/.vim/tmp/undo/%Users%wincent%code%wincent%aspects%
dotfiles%files%.zsh%aliases
```

**Comment by wincent** [comment]
Given the big rewrite for v6.0.x, I'm closing all older issues as there is unlikely to be anything significant happening on [the `5-x-devel` branch](https://github.com/wincent/command-t/tree/5-x-devel) from here on[^patches]. Feedback issue for 6.0.x is here:

- https://github.com/wincent/command-t/issues/393

[^patches]: Patches and PRs would be welcome, but my personal efforts are going to be directed towards `main`.
